 name: example-basic
on: [push]
jobs: 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/basic
          build: npx cypress info
